### ISSUE TITLE
What is selectors?

### ISSUE THREAD

**Issue by joelpierre** [filidorwiese/redux-wait-for-ssr#1]
Hey dude thanks for creating this. Looking into it now but have an issue. Where are you getting the below line from in your next.js example? There is no import or anything in your example. Thanks.

`const isContentLoaded = **selectors.isContentLoaded(currentState)**`

**Comment by filidorwiese** [comment]
Hi! The Redux selectors is something you'll have to write yourself. It depends on your Redux state, it could be something as:

```
export const isContentLoaded(state: StoreState): boolean => {
   return state.content.isLoaded;
}
```

And in the reducer you set this to `true` when the `actions.FETCH_CONTENT_RESOLVED` event has occurred. For example:

```
export function reducers(state: StoreState, action: Actions): StoreState {
    switch (action.type) {
        case constants.FETCH_CONTENT_RESOLVED: {
            state = {
                ...state,
                content: {
                    data: action.response,
                    isLoaded: true
                }
            }
            return state
        }
    }
}
```

This way you can keep track of requests that have been resolved in the state.

Note the above example is pure illustrative, your situation probably differs.

**Comment by joelpierre** [comment]
Thanks. I think it would be great if you made that clearer in your readme docs as I thought it was a prop you pass with your package.

**Comment by filidorwiese** [comment]
Will do!
