### ISSUE TITLE
action is not called 

### ISSUE THREAD

**Issue by chetank628** [filidorwiese/redux-wait-for-ssr#3]
```
async function  loadData(store,data,cookie) {
try {
		return await store.dispatch(waitFor([ServerInitialCartAction(data,cookie),getAllProductsAction(data,cookie)]))
	} catch (error) {
        console.log("loadData -> error", error)
	}
}
```
This is my loadata Function
 and this is how i added the middelware

```
let enhancer = createWaitForMiddleware().middleware;
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(
  reducer,
  window.Initial_data,
  composeEnhancers(applyMiddleware(thunk, logger,createWaitForMiddleware().enhancer)),
);
```

But the action are not getting called i checked the load data function is getting called properly anything which i am missing

**Comment by filidorwiese** [comment]
Sorry but it's hard to tell without seeing more of your code. For instance, what is in the `ServerInitialCartAction()` function? As you can see from the README, the signature of the `waitFor` is `waitFor(actions, timeout, errorAction)` where `actions` is an array of strings
